# demo.yaml
# This workflow will install Python dependencies, run tests with a variety of Python versions
name: Python app
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: test with pytest
      run: |
        make test
    - name: Format code with Black
      run: |
        make format
    - name: Train pipeline
      run: |
        ./bikeshare_model/train_pipeline.py
    - name: Predit pipeline
      run: |
        ./bikeshare_model/predict.py 
    - name: Build whl file
      run: |
        python -m build 
    - name: Build docker container 
      run: |
        cp ./bikeshare_model/*.whl ./bikeshare_model_api && \
        cd ./bikeshare_model_api && docker build -t bikeshare_model_api .
